http:
  middlewares:
    splunk-proto:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"

  routers:
    splunk:
      rule: "Host(`splunk.dermicapro.app`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      middlewares:
        - splunk-proto
      service: splunk

  services:
    splunk:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8000"
